[build]
  publish = "dist"
  command = "npm run build"

# WWW redirect
[[redirects]]
  from = "https://www.technedigital.com.br/*"
  to = "https://technedigital.com.br/:splat"
  status = 301
  force = true

# SPA fallback - DEVE VIR POR ÃšLTIMO
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
